### ISSUE TITLE
Visual Glitch in iOS 10

### ISSUE THREAD

**Issue by frankgumeta** [kshin/Hanabi#2]
Hi guys

After migrating my project to Xcode 8 and Swift 2.3 (not 3.0)
I have visual glitches when scrolling. Like overlaps in several cells

**Comment by ivanlisovyi** [comment]
Hi Frank,

I assume you are using the 1.1.1 version, am I right?

**Comment by frankgumeta** [comment]
Yep!

**Comment by frankgumeta** [comment]
So, should I definitely move to swift 3.0 version? :/

**Comment by ivanlisovyi** [comment]
@frankgumeta Hi Frank, I'm terribly sorry, but I didn't have time to look on this issue but moving to swift 3.0 is reasonable :)

**Comment by frankgumeta** [comment]
I updated to Swift 3.0, just to leave the solution here. Is not related to Swift Version. Is related to UICollectionView Prefetch!!!!

If someone experience this issue just needs to disable prefetching in the UICollectionView 

See you later!
